### ISSUE TITLE
Node Sync stuck in re-org loop

### ISSUE THREAD

**Issue by NWNZale** [zkSync-Community-Hub/zksync-developers#558]
Hello, upgraded to 24.6.0, but this is a problem with previous versions as well. The node hits the following loop and can't get past block 13098280.

```
zknode  | 2024-06-04T07:23:45.999512Z  INFO zksync_state::postgres: Storage values cache is too far behind (current L2 block is 0; requested update to 13098175); resetting the cache
zknode  | thread 'tokio-runtime-worker' panicked at core/lib/types/src/fee_model.rs:60:18:
zknode  | Can not convert PubdataIndependentBatchFeeModelInput into L1PeggedBatchFeeModelInput
zknode  | stack backtrace:
zknode  |    0: rust_begin_unwind
zknode  |              at ./rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:617:5
zknode  |    1: core::panicking::panic_fmt
zknode  |              at ./rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/panicking.rs:67:14
zknode  |    2: zksync_types::fee_model::BatchFeeInput::into_l1_pegged
zknode  |    3: multivm::glue::types::vm::block_context_mode::<impl multivm::glue::GlueFrom<multivm::interface::types::inputs::l1_batch_env::L1BatchEnv> for multivm::versions::vm_m5::vm_with_bootloader::BlockContextMode>::glue_from
zknode  |    4: <multivm::versions::vm_1_3_2::vm::Vm<S,H> as multivm::interface::traits::vm::VmInterface<S,H>>::new
zknode  |    5: multivm::vm_instance::VmInstance<S,H>::new_with_specific_version
zknode  |    6: zksync_core::api_server::execution_sandbox::apply::Sandbox::into_vm
zknode  |    7: zksync_core::api_server::execution_sandbox::execute::TransactionExecutor::execute_tx_in_sandbox::{{closure}}::{{closure}}::{{closure}}
zknode  |    8: tokio::runtime::task::core::Core<T,S>::poll
zknode  |    9: tokio::runtime::task::harness::Harness<T,S>::poll
```

```
zknode  | 2024-06-04T07:25:40.647967Z  INFO zksync_storage::db: All the RocksDB instances are dropped
zknode  | 2024-06-04T07:25:40.648048Z ERROR zksync_utils::wait_for_tasks: One of actors returned an error during shutdown: reorg_detector.run()
zknode  |
zknode  | Caused by:
zknode  |     reorg detected, restart the node to revert to the last correct L1 batch #196685.
```

**Comment by bxpana** [comment]
If you're still having issues with your node please open up a discussion in https://github.com/zkSync-Community-Hub/zkync-developers/discussions and we can help you there.
